In [1]:
import torch
from sklearn.datasets import make_classification

In [2]:
x,y=make_classification(n_samples=10, n_features=2 ,n_informative=2,n_redundant=0 ,n_classes=2, random_state=42)

In [3]:
x

array([[ 1.06833894, -0.97007347],
       [-1.14021544, -0.83879234],
       [-2.8953973 ,  1.97686236],
       [-0.72063436, -0.96059253],
       [-1.96287438, -0.99225135],
       [-0.9382051 , -0.54304815],
       [ 1.72725924, -1.18582677],
       [ 1.77736657,  1.51157598],
       [ 1.89969252,  0.83444483],
       [-0.58723065, -1.97171753]])

In [4]:
x.shape

(10, 2)

In [5]:
x=torch.tensor(x, dtype=torch.float32)
y=torch.tensor(y , dtype=torch.long) 

In [6]:
x

tensor([[ 1.0683, -0.9701],
        [-1.1402, -0.8388],
        [-2.8954,  1.9769],
        [-0.7206, -0.9606],
        [-1.9629, -0.9923],
        [-0.9382, -0.5430],
        [ 1.7273, -1.1858],
        [ 1.7774,  1.5116],
        [ 1.8997,  0.8344],
        [-0.5872, -1.9717]])

In [7]:
y

tensor([1, 0, 0, 0, 0, 1, 1, 1, 1, 0])

In [9]:
from torch.utils.data import Dataset, DataLoader


In [11]:
class cusotomdataset(Dataset):

    def __init__(self , features ,lables):
        super().__init__()
        self.features=features
        self.labels=lables
    
    def __len__(self):
        return self.features.shape[0]
    
    def __getitem__(self, index):
        return self.features[index] ,self.labels[index]

In [13]:
dataset=cusotomdataset(x,y)

In [15]:
len(dataset)

10

In [17]:
dataset[1]

(tensor([-1.1402, -0.8388]), tensor(0))

In [19]:
dataloader=DataLoader(dataset ,batch_size=2 , shuffle=True)

In [23]:
for batch_features ,batch_lables in dataloader:
    print(batch_features)
    print(batch_lables)
    print("-"*50)

tensor([[ 1.7273, -1.1858],
        [-1.9629, -0.9923]])
tensor([1, 0])
--------------------------------------------------
tensor([[-0.7206, -0.9606],
        [-0.9382, -0.5430]])
tensor([0, 1])
--------------------------------------------------
tensor([[-2.8954,  1.9769],
        [-1.1402, -0.8388]])
tensor([0, 0])
--------------------------------------------------
tensor([[ 1.8997,  0.8344],
        [-0.5872, -1.9717]])
tensor([1, 0])
--------------------------------------------------
tensor([[ 1.7774,  1.5116],
        [ 1.0683, -0.9701]])
tensor([1, 1])
--------------------------------------------------


A note about the collate function. 
 -> the collate fucntion in pytorch  dataloader is aa function that specifies how to combine a list of samples from dataset into a single batch
 

A note about the sampler 
  -> sampler in the dataloader determine the strategy for selecting  samples from the dataset   during the data loader. It controls how the indices of the dataset are drawn for each   batch.

Dataloader important parameters 

 => dataset(mandotory)
 => batch_size
 =>shuffle
 =>num_workers
 => pin_memory
 => drop_last
 =>collate_fn
 =>sampler


In [24]:

import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [26]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [29]:
df.drop(columns=['id', 'Unnamed: 32'], inplace=True, errors='ignore')



In [31]:
x_train ,X_test ,y_train ,y_test=train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2)

In [33]:
scaler = StandardScaler()
X_train = scaler.fit_transform(x_train)
X_test = scaler.transform(X_test)

c:\Users\LOQ\Desktop\PyTorch\env2\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [35]:

encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [37]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [39]:
from torch.utils.data import DataLoader ,Dataset

In [42]:
class cusotomdataset(Dataset):
    def __init__(self,features ,labels):
        super().__init__()
        self.features=features
        self.labels=labels
    def __len__(self):
        return self.features.shape[0]
    
    def __getitem__(self, index):
        return self.features[index] ,self.labels[index]
    

In [44]:
train_dataset=cusotomdataset(X_train_tensor,y_train_tensor)

In [46]:
test_dataset=cusotomdataset(X_test_tensor,y_test_tensor)

In [ ]:
import torch.nn as nn
