In [2]:
print('hello')

hello


In [3]:
import torch
points1=torch.tensor([[1.0,2.0],[3.0,4.0],[5.0,7.0]])

In [4]:
points_storage1=points1.storage

In [5]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
points_storage = points.storage()
points_storage[0] = 2.0

C:\Users\LOQ\AppData\Local\Temp\ipykernel_6320\3775807201.py:2: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  points_storage = points.storage()


In [6]:
points

tensor([[2., 4.],
        [2., 1.],
        [3., 5.]])

In [7]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
second_points=points[1]
second_points.storage_offset()


2

In [8]:
second_points.size()

torch.Size([2])

In [9]:
points.stride()

(2, 1)

In [10]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
second_points=points[1]
second_points[0]=10.0
points


tensor([[ 1.,  4.],
        [10.,  1.],
        [ 3.,  5.]])

In [11]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
second_points1=points[1].clone()
second_points1[0]=10.0
points

tensor([[1., 4.],
        [2., 1.],
        [3., 5.]])

In [12]:
# transpose
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
points_t=points.t()
points_t

tensor([[1., 2., 3.],
        [4., 1., 5.]])

In [13]:
# Numeric types
double_points=torch.ones(10,2, dtype=torch.double)
double_points.dtype

torch.float64

In [14]:
# indexing tensor
some_list=list(range(5))
some_list

[0, 1, 2, 3, 4]

In [15]:
some_list[:]
some_list[1:4]
some_list[:4]
some_list[:3]
some_list[1:4:2]

[1, 3]

In [16]:
# numpy interoprability

points=torch.ones(3,4)
points_np=points.numpy()
points_np

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [17]:
import csv
wine_path="../data/"

In [19]:
# learning is the estimation

t_c = [0.5, 14.0, 15.0, 28.0, 11.0, 8.0, 3.0, -4.0, 6.0, 13.0, 21.0]
t_u = [35.7, 55.9, 58.2, 81.9, 56.3, 48.9, 33.9, 21.8, 48.4, 60.4, 68.4]
t_c = torch.tensor(t_c)
t_u = torch.tensor(t_u)

In [20]:
def model(t_u ,w,b):
    return w*t_u +b 

In [21]:
def loss(t_p,t_c):
    squared_difference=(t_p-t_c)**2
    return squared_difference.mean()

In [22]:
w=torch.ones(1)
b=torch.zeros(1)

In [23]:
t_p=model(t_u ,w,b)

In [25]:
t_p

tensor([35.7000, 55.9000, 58.2000, 81.9000, 56.3000, 48.9000, 33.9000, 21.8000,
        48.4000, 60.4000, 68.4000])

In [28]:
import torch


In [30]:
# Autograd in pytorch

x=torch.tensor(3.0 , requires_grad=True)



In [32]:
x

tensor(3., requires_grad=True)

In [34]:
y=x**2

In [36]:
y

tensor(9., grad_fn=<PowBackward0>)

In [42]:
x.grad

tensor(6.)

In [44]:
x=torch.tensor(3.0, requires_grad=True)
y=x**2
z=torch.sin(y)

In [46]:
z

tensor(0.4121, grad_fn=<SinBackward0>)

In [49]:
x.grad

tensor(-5.4668)

In [51]:
# using autograd calculate loss

x=torch.tensor(6.7)
y=torch.tensor(0.0)
 

In [53]:
w=torch.tensor(1.0 ,requires_grad=True)
b=torch.tensor(0.0 , requires_grad=True)

In [55]:
z=w*x+b

In [57]:
z

tensor(6.7000, grad_fn=<AddBackward0>)

In [60]:
y_pred=torch.sigmoid(z)
y_pred

tensor(0.9988, grad_fn=<SigmoidBackward0>)

In [66]:
import torch.nn.functional as F

loss1 = F.binary_cross_entropy(y_pred, y)
loss1


tensor(6.7012, grad_fn=<BinaryCrossEntropyBackward0>)

In [67]:
w.grad

In [72]:
# clearing grad
x=torch.tensor(2.0 , requires_grad=True)
x


tensor(2., requires_grad=True)

In [74]:
y=x**2
y

tensor(4., grad_fn=<PowBackward0>)

In [76]:
y.backward()

RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.

In [78]:
x.grad

tensor(4.)