pytorch NN module


In [4]:
import torch
import torch.nn as nn

In [10]:
# create model class

class module(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.linear=nn.Linear(num_features ,1)
        self.sigmoid=nn.Sigmoid()
    def forward(self, features):
        out=self.linear(features)
        out=self.sigmoid(out)

        return out



In [14]:
features=torch.rand(10,5)
model=module(features.shape[1])
model(features)

tensor([[0.5993],
        [0.5887],
        [0.5803],
        [0.6094],
        [0.6143],
        [0.5992],
        [0.5274],
        [0.6252],
        [0.5861],
        [0.5605]], grad_fn=<SigmoidBackward0>)

In [16]:
model.linear.weight

Parameter containing:
tensor([[-0.3932,  0.1022,  0.1424, -0.0492,  0.0661]], requires_grad=True)

In [19]:
from torchinfo import summary


In [22]:
summary(model , input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
module                                   [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [27]:
# advanced nn module with neurons

import torch
import torch.nn as nn

In [30]:
class module(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.linear1=nn.Linear(num_features ,3)
        self.relu=nn.ReLU()
        self.linear2=nn.Linear(3,1)
        self.sigmoid=nn.Sigmoid()
    def forward(self , features):
        out=self.linear1(features)
        out=self.relu(out)
        out=self.linear2(out)
        out=self.sigmoid(out)
        return out

In [36]:
features=torch.rand(10,5)
model1=module(features.shape[1])
model1(features)

tensor([[0.6701],
        [0.6377],
        [0.6776],
        [0.6658],
        [0.6852],
        [0.6793],
        [0.6865],
        [0.6453],
        [0.6808],
        [0.6989]], grad_fn=<SigmoidBackward0>)

In [37]:
model1.linear1.weight

Parameter containing:
tensor([[-0.2928,  0.0161,  0.2013, -0.1382, -0.0384],
        [ 0.0970,  0.4332, -0.0506,  0.3459,  0.2103],
        [-0.0595,  0.2999,  0.2188, -0.4068,  0.1000]], requires_grad=True)

In [39]:
summary(model1 , input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
module                                   [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [43]:
# Sequential container

class module1(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.network =nn.Sequential(
            nn.Linear(num_features ,3),
            nn.ReLU(),
            nn.Linear(3,1),
            nn.Sigmoid(),
        )
    def forward(self , features):
        out=self.network(features)
        return out

In [46]:
features=torch.rand(10,5)
model2=module1(features.shape[1])
model2(features)

tensor([[0.3679],
        [0.3679],
        [0.3679],
        [0.3662],
        [0.3612],
        [0.3679],
        [0.3679],
        [0.3679],
        [0.3679],
        [0.3679]], grad_fn=<SigmoidBackward0>)

In [ ]:

import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [49]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [51]:
df.drop(columns=['id', 'Unnamed: 32'], inplace=True, errors='ignore')


In [53]:
x_train ,X_test ,y_train ,y_test=train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2)

In [55]:
scaler = StandardScaler()
X_train = scaler.fit_transform(x_train)
X_test = scaler.transform(X_test)

c:\Users\LOQ\Desktop\adavance_pytohn\env2\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [57]:

encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [59]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [64]:
class MYSIMPLENN(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.linear=nn.Linear(num_features ,1)
        self.sigmoid=nn.Sigmoid()
    def forward(self ,x):
        out=self.linear(x)
        out=self.sigmoid(out)
        return out
    def loss_function(self, y_pred, y):
    # Clamp predictions to avoid log(0)
     epsilon = 1e-7
     y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

    # Calculate loss
     loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
    
     return loss
    

In [71]:
# important parameters
learing_rate=0.1
epoches=25


In [72]:
num_features = X_train_tensor.shape[1]


In [74]:
model=MYSIMPLENN(num_features)


In [ ]:
for epoch in range(epoches):

  # forward pass
  y_pred = model.forward()

  # loss calculate
  loss = model.loss_function(y_pred, y_train_tensor)

  # backward pass
  loss.backward()

  # parameters update
  with torch.no_grad():
    model.linear.weights -= learing_rate * model.weights.grad
    model.linear.bias -= learing_rate * model.bias.grad

  # zero gradients
  model.linear.weights.grad.zero_()
  model.linear.bias.grad.zero_()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}') 

In [85]:
# using torch nn module in  loss function or using built_in loss function
loss_function=nn.BCELoss()

In [84]:
type(loss_function)

torch.nn.modules.loss.BCELoss

In [86]:
# using built-in optimizer
optimizer=torch.optim.SGD( model.parameters(), lr=learing_rate)

# in loop function we use only the optimizer function

optimizer.step()
optimizer.zero_grad()

